### ISSUE TITLE
Dcroat overlap bug

### ISSUE THREAD

**Issue by emmamarichal** [silnrsi/font-nuosu#1]
Hello!

I noticed a problem with overlapping components.

![Dcroat_Issue](https://user-images.githubusercontent.com/64773544/165731855-3f5eb0ec-ec97-4d88-b16c-56d385e75e88.jpeg)

**Comment by jvgaultney** [comment]
Thanks - that will be fixed in the next release, but that may not be for a few months. Can you still onboard the font to GF now, or do you need us to fix this first? Since it is an extended Latin character that will rarely - if ever - be used in this Yi-script font it should not cause problems for anyone.

**Comment by emmamarichal** [comment]
Hello! Yes we can onboard it like that, and keep this problem in mind for the next release.

**Comment by jvgaultney** [comment]
Thank you!

**Comment by devosb** [comment]
`Dcroat` in AGLFN is for the character U+0110 LATIN CAPITAL LETTER D WITH STROKE, which is not in this font. U+00D0 LATIN CAPITAL LETTER ETH (AGLFN `Eth`) is in the font, and the issue here has been fixed in https://github.com/silnrsi/font-nuosu/commit/86d6f44945bfe6e8997f5241f7a9a16107d33eeb The issue was not in the glyph mentioned in this issue, but rather in a component glyph (D). The D, and many other glyphs, need to have curve directions fixed.
